# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Emma Matthews @ GitHub Pages
email: emma@gmail.com
author: Emma Matthews
description: > # This is the official Emma Matthews GitHub Page! W00t!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: emmaontwitter
github_username:  ejmatthews0606

# Build settings
markdown: kramdown
